# Stolen from capitaomorte/yasnippet
language: emacs-lisp

branches:
  except:
    - data

env:
  - EMACS_24_X=1
  - EMACS_24_X=2
  - EMACS_24_X=3
  - EMACS_24_X=4

before_install:
  - export PATH="$HOME/.evm/bin:$PATH"
  - export PATH="$HOME/.cask/bin:$PATH"
  - sudo mkdir /usr/local/evm
  - sudo chown travis:travis /usr/local/evm
  - make install_evm
  - evm install emacs-24.$EMACS_24_X-bin --skip --use
  - make install_cask
  - cask info
  - cask install
  - emacs --version
  - cask --version

script:
  - make $EMACS_24_X
  
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/07063bd143e35f54b1e8
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
